#!/bin/bash

INPUT_DIR="/System/Library/ColorSync/Profiles"
OUTPUT_C="picasso_icc_profiles.c"
OUTPUT_H="picasso_icc_profiles.h"
OUTPUT_ENUM_H="picasso_icc_enum.h"
OUTPUT_SWITCH_H="picasso_icc_switch.h"
OUTPUT_ENUM_TO_STRING_C="picasso_icc_enum_to_string.c"

# Init output files
echo "// AUTOGENERATED - ICC profile data" > "$OUTPUT_C"
echo "#pragma once" > "$OUTPUT_H"
echo "// AUTOGENERATED - ICC profile header" >> "$OUTPUT_H"

echo "// AUTOGENERATED ENUM" > "$OUTPUT_ENUM_H"
echo "#pragma once" >> "$OUTPUT_ENUM_H"
echo "typedef enum {" >> "$OUTPUT_ENUM_H"
echo "    PICASSO_PROFILE_NONE = 0," >> "$OUTPUT_ENUM_H"

echo "// AUTOGENERATED SWITCH" > "$OUTPUT_SWITCH_H"
echo "// Use inside a switch(profile)" >> "$OUTPUT_SWITCH_H"

echo "#include \"picasso_icc_enum.h\"" > "$OUTPUT_ENUM_TO_STRING_C"
echo "" >> "$OUTPUT_ENUM_TO_STRING_C"
echo "const char *picasso_icc_profile_name(picasso_icc_profile profile) {" >> "$OUTPUT_ENUM_TO_STRING_C"
echo "    switch (profile) {" >> "$OUTPUT_ENUM_TO_STRING_C"
echo "        case PICASSO_PROFILE_NONE: return \"None\";" >> "$OUTPUT_ENUM_TO_STRING_C"

# Loop through ICC/ICM files
for file in "$INPUT_DIR"/*.icc "$INPUT_DIR"/*.icm; do
    [ -e "$file" ] || continue

    base=$(basename "$file")
    name="${base%.*}"

    ident=$(echo "$name" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g' | sed 's/^_//;s/_$//')
    enum_name=$(echo "$ident" | tr '[:lower:]' '[:upper:]')

    echo "Processing $base → $ident"

    # Embed binary data
    xxd -i "$file" |
    sed "s/^unsigned char .* =/const unsigned char picasso_icc_${ident}[] =/" |
    sed "s/^unsigned int .* =/const unsigned int picasso_icc_${ident}_len =/" \
    >> "$OUTPUT_C"

    # Add declarations
    echo "extern const unsigned char picasso_icc_${ident}[];" >> "$OUTPUT_H"
    echo "extern const unsigned int  picasso_icc_${ident}_len;" >> "$OUTPUT_H"

    # Append enum
    echo "    PICASSO_PROFILE_${enum_name}," >> "$OUTPUT_ENUM_H"

    # Add switch case
    echo "    case PICASSO_PROFILE_${enum_name}:" >> "$OUTPUT_SWITCH_H"
    echo "        icc_data = picasso_icc_${ident};" >> "$OUTPUT_SWITCH_H"
    echo "        icc_size = picasso_icc_${ident}_len;" >> "$OUTPUT_SWITCH_H"
    echo "        break;" >> "$OUTPUT_SWITCH_H"

    # Add string mapping
    echo "        case PICASSO_PROFILE_${enum_name}: return \"${name}\";" >> "$OUTPUT_ENUM_TO_STRING_C"
done

# Close the enum and string function
echo "} picasso_icc_profile;" >> "$OUTPUT_ENUM_H"
echo "        default: return \"Unknown\";" >> "$OUTPUT_ENUM_TO_STRING_C"
echo "    }" >> "$OUTPUT_ENUM_TO_STRING_C"
echo "}" >> "$OUTPUT_ENUM_TO_STRING_C"

echo "✅ Generated:"
echo " - $OUTPUT_C"
echo " - $OUTPUT_H"
echo " - $OUTPUT_ENUM_H"
echo " - $OUTPUT_SWITCH_H"
echo " - $OUTPUT_ENUM_TO_STRING_C"
