// AUTOGENERATED SWITCH
// Use inside a switch(profile)
    case PICASSO_PROFILE_ACESCG_LINEAR:
        icc_data = picasso_icc_acescg_linear;
        icc_size = picasso_icc_acescg_linear_len;
        break;
    case PICASSO_PROFILE_ADOBERGB1998:
        icc_data = picasso_icc_adobergb1998;
        icc_size = picasso_icc_adobergb1998_len;
        break;
    case PICASSO_PROFILE_DCI_P3_RGB:
        icc_data = picasso_icc_dci_p3_rgb;
        icc_size = picasso_icc_dci_p3_rgb_len;
        break;
    case PICASSO_PROFILE_DISPLAY_P3:
        icc_data = picasso_icc_display_p3;
        icc_size = picasso_icc_display_p3_len;
        break;
    case PICASSO_PROFILE_GENERIC_CMYK:
        icc_data = picasso_icc_generic_cmyk_profile;
        icc_size = picasso_icc_generic_cmyk_profile_len;
        break;
    case PICASSO_PROFILE_GENERIC_GRAY_GAMMA_2_2:
        icc_data = picasso_icc_generic_gray_gamma_2_2_profile;
        icc_size = picasso_icc_generic_gray_gamma_2_2_profile_len;
        break;
    case PICASSO_PROFILE_GENERIC_GRAY:
        icc_data = picasso_icc_generic_gray_profile;
        icc_size = picasso_icc_generic_gray_profile_len;
        break;
    case PICASSO_PROFILE_GENERIC_LAB:
        icc_data = picasso_icc_generic_lab_profile;
        icc_size = picasso_icc_generic_lab_profile_len;
        break;
    case PICASSO_PROFILE_GENERIC_RGB:
        icc_data = picasso_icc_generic_rgb_profile;
        icc_size = picasso_icc_generic_rgb_profile_len;
        break;
    case PICASSO_PROFILE_GENERIC_XYZ:
        icc_data = picasso_icc_generic_xyz_profile;
        icc_size = picasso_icc_generic_xyz_profile_len;
        break;
    case PICASSO_PROFILE_ITU_2020:
        icc_data = picasso_icc_itu_2020;
        icc_size = picasso_icc_itu_2020_len;
        break;
    case PICASSO_PROFILE_ITU_709:
        icc_data = picasso_icc_itu_709;
        icc_size = picasso_icc_itu_709_len;
        break;
    case PICASSO_PROFILE_ROMM_RGB:
        icc_data = picasso_icc_romm_rgb;
        icc_size = picasso_icc_romm_rgb_len;
        break;
    case PICASSO_PROFILE_SRGB:
        icc_data = picasso_icc_srgb_profile;
        icc_size = picasso_icc_srgb_profile_len;
        break;
